// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaceRail.AssetMonitoring.Api.Data;

#nullable disable

namespace PaceRail.AssetMonitoring.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaceRail.AssetMonitoring.Api.Models.InspectionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InspectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RailAssetId")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresImmediateAction")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RailAssetId");

                    b.ToTable("InspectionLogs");
                });

            modelBuilder.Entity("PaceRail.AssetMonitoring.Api.Models.RailAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ELR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("EndChainageMiles")
                        .HasColumnType("double precision");

                    b.Property<double>("StartChainageMiles")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RailAssets");
                });

            modelBuilder.Entity("PaceRail.AssetMonitoring.Api.Models.InspectionLog", b =>
                {
                    b.HasOne("PaceRail.AssetMonitoring.Api.Models.RailAsset", null)
                        .WithMany("Inspections")
                        .HasForeignKey("RailAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PaceRail.AssetMonitoring.Api.Models.RailAsset", b =>
                {
                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
